// This file is generated by pnpm sync:posts. Do not edit manually.
import type { ComponentType } from "react";

import Article001 from "./2014/7-principles-of-rich-web-applications/article.mdx";
import Article002 from "./2015/ecmascript-6/article.mdx";
import Article003 from "./2015/pure-ui/article.mdx";
import Article004 from "./2016/addressable-errors/article.mdx";
import Article005 from "./2017/2016-in-review/article.mdx";
import Article006 from "./2017/its-hard-to-forego-efficiency/article.mdx";
import Article007 from "./2020/2019-in-review/article.mdx";
import Article008 from "./2020/an-ode-to-code-golf/article.mdx";
import Article009 from "./2020/develop-preview-test/article.mdx";
import Article010 from "./2020/next-for-vercel/article.mdx";
import Article011 from "./2020/static-hoisting/article.mdx";
import Article012 from "./2020/vercel/article.mdx";
import Article013 from "./2021/making-the-web-faster/article.mdx";

type ArticleComponent = ComponentType;

const articleComponents: Record<string, ArticleComponent> = {
  "2014/7-principles-of-rich-web-applications": Article001,
  "2015/ecmascript-6": Article002,
  "2015/pure-ui": Article003,
  "2016/addressable-errors": Article004,
  "2017/2016-in-review": Article005,
  "2017/its-hard-to-forego-efficiency": Article006,
  "2020/2019-in-review": Article007,
  "2020/an-ode-to-code-golf": Article008,
  "2020/develop-preview-test": Article009,
  "2020/next-for-vercel": Article010,
  "2020/static-hoisting": Article011,
  "2020/vercel": Article012,
  "2021/making-the-web-faster": Article013,
};

export function getArticleComponent(year: string, slug: string) {
  return articleComponents[`${year}/${slug}`];
}
